# Generated by Django 2.2.8 on 2020-09-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.CharField(choices=[('L', 'LARGE'), ('S', 'SMALL'), ('XL', 'XTRA-SMALL')], max_length=2)),
            ],
        ),
    ]
