# Generated by Django 2.2.8 on 2020-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='size',
            field=models.CharField(choices=[('L', 'LARGE'), ('S', 'SMALL'), ('XL', 'XTRA-SMALL')], default='L', max_length=2),
        ),
    ]
